### ISSUE TITLE
Question on the model checkpoint

### ISSUE THREAD

**Issue by gpengzhi** [fe1ixxu/ALMA#1]
Great work!

Is there any plan to release the model checkpoint only with monolingual data finetuning?

**Comment by fe1ixxu** [comment]
Thanks for the interest! [haoranxu/ALMA-7B-Pretrain](https://huggingface.co/haoranxu/ALMA-7B-Pretrain) and [haoranxu/ALMA-13B-Pretrain](https://huggingface.co/haoranxu/ALMA-13B-Pretrain) are the models which are only fine-tuned on monolingual data. To clarify, [haoranxu/ALMA-7B-Pretrain-LoRA](https://huggingface.co/haoranxu/ALMA-7B-Pretrain-LoRA) and [haoranxu/ALMA-13B-Pretrain-LoRA](https://huggingface.co/haoranxu/ALMA-13B-Pretrain-LoRA) are just LoRA for them in the MT task~
