### ISSUE TITLE
Release `Random` and `Filtered` parallel corpora

### ISSUE THREAD

**Issue by zwhe99** [fe1ixxu/ALMA#14]
Thanks for your work! I notice that you also conducted an ablation for parallel data in Table 3, where you used `Random` and `Filtered` variants for parallel data. Can you release these data so that we can better reproduce the results?

**Comment by fe1ixxu** [comment]
They are Microsoft's internal datasets. I will discuss with my colleagues the best way to release them. Thank you!

**Comment by zwhe99** [comment]
Thank you for your reply.
