### ISSUE TITLE
How much CPO data set is expected to be needed when creating a one-to-one machine translator?

### ISSUE THREAD

**Issue by qwopqwop200** [fe1ixxu/ALMA#26]
Thank you for your amazing work.

I am thinking of creating a bidirectional translator using ALMA-R that supports only single pairs. How many CPO datasets do you expect to need for this?

Do I need 22k datasets like in ALMA-R? Or is a smaller number of data sufficient?

**Comment by fe1ixxu** [comment]
Thank you for the interest!

If you want ALMA to support languages beyond German, Chinese, Czech, Russian and Icelandic (what ALMA originally supported), The best way is to firstly fine-tune the monolingual data on your target language. If your target language is one of them, a smaller dataset like 2K CPO data should be totally fine.

**Comment by fe1ixxu** [comment]
Yes, it should be sufficient. But please be careful about the quality of the CPO data.
