### ISSUE TITLE
Loading ALMA-7B-R (LORA merged) through huggingface downloads Pretrained + LORA

### ISSUE THREAD

**Issue by tranvaj** [fe1ixxu/ALMA#30]
This started happening as of today or yesterday, before that it normally installed LORA merged and worked fine

Code im using:
```import torch
from transformers import AutoModelForCausalLM
from transformers import AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("haoranxu/ALMA-7B-R", torch_dtype="auto", device_map="auto")
tokenizer = AutoTokenizer.from_pretrained("haoranxu/ALMA-7B-R", padding_side='left')```

**Comment by fe1ixxu** [comment]
Thanks for your interest!

I guess this is because the checkpoint of the adapter is also located under `ALMA-7B-R`. This should not affect the performance of ALMA-R and just a way of providing the checkpoint of the adapter model.
