### ISSUE TITLE
[Bug/Feature] The dataset isn't reading the same cache_dir

### ISSUE THREAD

**Issue by alvations** [fe1ixxu/ALMA#35]
The default behavior of the `datasets.Dataset.map` functions are pointing to the `cache_dir` of the Huggingface environment variable. 

But sometimes uses point the cache_dir to the model which uses the `model_args.cache_dir` and run the scripts:

```
python run_llmmt.py --cache_dir myowndir
``` 

And when it comes to the dataset reading part it'll throw some issues when `myowndir` isn't set as the default `HF_DATASETS_CACHE`, so users might have to do something like:

```
export HF_DATASETS_CACHE=myowndir python run_llmmt.py --cache_dir myowndir
```

Perhaps 

1) Changing the following to point to `model_args.cache_dir` or `data_args.cache_dir` might work better
  - https://github.com/fe1ixxu/ALMA/blob/master/utils/utils.py#L650
  - https://github.com/fe1ixxu/ALMA/blob/master/utils/utils.py#L674
  - https://github.com/fe1ixxu/ALMA/blob/master/utils/utils.py#L674

2) Or having a note on the cache_dir in the README.md at https://github.com/fe1ixxu/ALMA/tree/master?tab=readme-ov-file#cpo-fine-tuning might be helpful to future users.

**Comment by fe1ixxu** [comment]
Thank you for your suggestions! The reason could be that I pre-define the cache location here: https://github.com/fe1ixxu/ALMA/blob/b92304c6548b7d0af0cdadca9d63c07c70d19cd5/runs/parallel_ft_lora.sh#L4

and this triggers that your cached files are not in your own dir.

We will include a clearer README to indicate this situation.

**Comment by alvations** [comment]
Thanks, having a note for the users would be good!
