### ISSUE TITLE
About the interleave probability selections

### ISSUE THREAD

**Issue by Aniruddha-JU** [fe1ixxu/ALMA#4]
Congrats on the great work and thanks for sharing the nice Github repo!

I have one question how do you decide the interleave probability percentage? Do you follow any rules or previous work?

**Comment by Aniruddha-JU** [comment]
I am asking for the stage 1 pre-training

**Comment by fe1ixxu** [comment]
Thanks for your interest!! Please find the reasons for interleave probability selection for stage 1 in Appendix D.1 in the paper!
