### ISSUE TITLE
GPUs used during parallel data fine-tuning

### ISSUE THREAD

**Issue by liangyingshao** [fe1ixxu/ALMA#55]
Thank you for your outstanding work. Could you please provide details on the following?
1. The number of GPUs used during the parallel data fine-tuning.
2. The type of the GPUs used during the parallel data fine-tuning.

**Comment by fe1ixxu** [comment]
Hi, thanks for your interest!

1. 16 GPUs were used during the parallel data fine-tuning.
2. The models were trained on MI200 GPUs.
