### ISSUE TITLE
Oscar data structure does not match "utils.py" code and datasets module

### ISSUE THREAD

**Issue by risotoonero** [fe1ixxu/ALMA#64]
As the title says，The “oscar-corpus/OSCAR-2301” data structure is as follows：
{
   "content":"English sentence\nphrase en français\n????????????", // (1)
   "warc_headers":{ // (2)
      "warc-identified-content-language":"fra,eng",
      "warc-target-uri":"https://fr.wikipedia.org/wiki/...",
      "warc-record-id":"<urn:uuid:29eaa920-d299-4b1d-b687-c72bd8d68116>",
      "warc-type":"conversion",
      "content-length":"35298", // (3)
      "warc-refers-to":"<urn:uuid:39e42055-0d94-4e45-9c6c-9e7056635d64>",
      "warc-block-digest":"sha1:WFH2A5WHCS2H365GIAFYQPI7UOAMFGHB", // (3)
      "warc-date":"2022-11-26T09:45:47Z",
      "content-type":"text/plain"
   },
   "metadata":{
      "identification":{ // (4)
         "label":"fr",
         "prob":0.8938327
      },
      "harmful_pp":4063.1814, // (5)
      "tlsh":"tlsh:T125315FF2B6088901EEA097015DB39B4600B...", // (6)
      "quality_warnings":[ // (7)
         "short_sentences",
         "header",
         "footer"
      ],
      "categories":[ // (8)
         "examen_pix",
         "liste_bu"
      ],
      "sentence_identifications":[ // (9)
         {
            "label":"fr",
            "prob":0.99837273
         },
         {
            "label":"en",
            "prob":0.9992377
         },
         null
      ]
   }
}
When I performed the first stage of monolingual data fine-tuning, the following error occurred：
![1729948985586](https://github.com/user-attachments/assets/a53208b3-5953-43f5-a625-8bc44217ee11)
![1729949071661](https://github.com/user-attachments/assets/103c0b9d-dcac-4e7c-959a-2f5d2445579b)
The “oscar-corpus/OSCAR-2201” data structure is the same format, how should I solve it?Thanks for the author's reply

**Comment by yuanzhiyong1999** [comment]
How did you solve it?

**Comment by risotoonero** [comment]
> 你是怎么解决的？

Change the names of the relevant fields in utils.py, or convert the Oscar data structure to ['id', 'text', 'lang'], and then change utils.py,but I haven't run it successfully yet

**Comment by yuanzhiyong1999** [comment]
thank you for your reply，I am also trying to solve this problem. However, the Oscar data was last updated a year ago. I don't understand why it doesn't match the current code.
